from typing import Protocol


class StarsGateway(Protocol):
    """Telegram Bot API operations that involve Stars (implemented with aiogram in app/bot/gateway.py)."""

    async def gift_premium(self, user_id: int, months: int, star_count: int) -> None: ...

    async def star_balance(self) -> int: ...

    async def refund_star_payment(self, user_id: int, charge_id: str) -> None: ...

    async def create_invoice_link(self, title: str, description: str, payload: str, amount: int) -> str: ...

    async def send_invoice(self, chat_id: int, title: str, description: str, payload: str, amount: int) -> int: ...
