"""User-facing bot strings (uz/ru/en). Admin screens are Uzbek-only and live in the admin handlers."""

from app.i18n import register

register(
    {
        "choose_lang": {
            "uz": "🌐 Tilni tanlang · Выберите язык · Choose language",
            "ru": "🌐 Tilni tanlang · Выберите язык · Choose language",
            "en": "🌐 Tilni tanlang · Выберите язык · Choose language",
        },
        "welcome": {
            "uz": "Assalomu alaykum, {name}! 👋\n\n<b>Soft-tg-Market</b> — 💎 Telegram Premium va ⭐ Stars eng arzon narxda.\n\n⚡️ 1–3 daqiqada faollashadi\n🔒 Rasmiy Telegram tizimi orqali\n💳 TON, Stars yoki balans bilan to'lov\n\n💼 Balansingiz: <b>{balance}</b>",
            "ru": "Здравствуйте, {name}! 👋\n\n<b>Soft-tg-Market</b> — 💎 Telegram Premium и ⭐ Stars по лучшей цене.\n\n⚡️ Активация за 1–3 минуты\n🔒 Через официальную систему Telegram\n💳 Оплата TON, Stars или с баланса\n\n💼 Ваш баланс: <b>{balance}</b>",
            "en": "Hello, {name}! 👋\n\n<b>Soft-tg-Market</b> — 💎 Telegram Premium and ⭐ Stars at the lowest price.\n\n⚡️ Activated in 1–3 minutes\n🔒 Via Telegram's official system\n💳 Pay with TON, Stars or balance\n\n💼 Your balance: <b>{balance}</b>",
        },
        "b_app": {"uz": "🚀 Ilovani ochish", "ru": "🚀 Открыть приложение", "en": "🚀 Open app"},
        "b_premium": {"uz": "💎 Premium sotib olish", "ru": "💎 Купить Premium", "en": "💎 Buy Premium"},
        "b_stars": {"uz": "⭐ Stars sotib olish", "ru": "⭐ Купить Stars", "en": "⭐ Buy Stars"},
        "b_wallet": {"uz": "💼 Hamyon · {balance}", "ru": "💼 Кошелёк · {balance}", "en": "💼 Wallet · {balance}"},
        "b_orders": {"uz": "📦 Buyurtmalarim", "ru": "📦 Мои заказы", "en": "📦 My orders"},
        "b_ref": {"uz": "👥 Do'stlarni taklif qilish", "ru": "👥 Пригласить друзей", "en": "👥 Invite friends"},
        "b_settings": {"uz": "⚙️ Sozlamalar", "ru": "⚙️ Настройки", "en": "⚙️ Settings"},
        "b_help": {"uz": "🆘 Yordam", "ru": "🆘 Помощь", "en": "🆘 Help"},
        "b_admin": {"uz": "🛠 Admin panel", "ru": "🛠 Админ-панель", "en": "🛠 Admin panel"},
        "b_back": {"uz": "« Orqaga", "ru": "« Назад", "en": "« Back"},
        "b_cancel": {"uz": "✖️ Bekor qilish", "ru": "✖️ Отмена", "en": "✖️ Cancel"},
        "b_home": {"uz": "🏠 Bosh menyu", "ru": "🏠 Главное меню", "en": "🏠 Main menu"},
        "b_self": {"uz": "🙋 O'zimga (@{u})", "ru": "🙋 Себе (@{u})", "en": "🙋 For me (@{u})"},
        "b_self_nouser": {"uz": "🙋 O'zimga", "ru": "🙋 Себе", "en": "🙋 For me"},
        "b_other": {"uz": "🎁 Boshqa odamga", "ru": "🎁 Другому человеку", "en": "🎁 For someone else"},
        "b_contact": {"uz": "👤 Kontaktdan tanlash", "ru": "👤 Выбрать из контактов", "en": "👤 Pick a contact"},
        "b_continue": {"uz": "✅ Ha, davom etish", "ru": "✅ Да, продолжить", "en": "✅ Yes, continue"},
        "b_other_username": {"uz": "✏️ Boshqa username", "ru": "✏️ Другой username", "en": "✏️ Another username"},
        "b_promo": {"uz": "🎟 Promokod kiritish", "ru": "🎟 Ввести промокод", "en": "🎟 Enter promo code"},
        "b_pay_wallet": {
            "uz": "💎 Hamyon orqali to'lash",
            "ru": "💎 Оплатить через кошелёк",
            "en": "💎 Pay with wallet",
        },
        "b_check": {"uz": "🔄 To'lovni tekshirish", "ru": "🔄 Проверить оплату", "en": "🔄 Check payment"},
        "b_cancel_order": {"uz": "✖️ Buyurtmani bekor qilish", "ru": "✖️ Отменить заказ", "en": "✖️ Cancel order"},
        "b_copy_addr": {"uz": "📋 Manzil", "ru": "📋 Адрес", "en": "📋 Address"},
        "b_copy_comment": {"uz": "📋 Izoh", "ru": "📋 Комментарий", "en": "📋 Comment"},
        "b_copy_amount": {"uz": "📋 Summa", "ru": "📋 Сумма", "en": "📋 Amount"},
        "b_tonkeeper": {"uz": "Tonkeeper'da ochish", "ru": "Открыть в Tonkeeper", "en": "Open in Tonkeeper"},
        "b_pay_balance": {"uz": "✅ To'lash · {amount}", "ru": "✅ Оплатить · {amount}", "en": "✅ Pay · {amount}"},
        "b_pay_stars": {"uz": "⭐ {amount} to'lash", "ru": "⭐ Оплатить {amount}", "en": "⭐ Pay {amount}"},
        "b_buy_again": {"uz": "💎 Yana sotib olish", "ru": "💎 Купить ещё", "en": "💎 Buy again"},
        "b_invite": {"uz": "👥 Taklif qilish", "ru": "👥 Пригласить", "en": "👥 Invite"},
        "b_topup": {"uz": "➕ Balansni to'ldirish", "ru": "➕ Пополнить баланс", "en": "➕ Top up balance"},
        "b_history": {"uz": "📜 Tarix", "ru": "📜 История", "en": "📜 History"},
        "b_share": {"uz": "📤 Do'stlarga ulashish", "ru": "📤 Поделиться", "en": "📤 Share"},
        "b_copy_link": {"uz": "📋 Havolani nusxalash", "ru": "📋 Скопировать ссылку", "en": "📋 Copy link"},
        "b_support": {
            "uz": "💬 Support bilan bog'lanish",
            "ru": "💬 Связаться с поддержкой",
            "en": "💬 Contact support",
        },
        "b_lang": {"uz": "🌐 Til", "ru": "🌐 Язык", "en": "🌐 Language"},
        "b_mkt_on": {"uz": "🔔 Aksiya xabarlari: ✅", "ru": "🔔 Рассылки: ✅", "en": "🔔 Promo messages: ✅"},
        "b_mkt_off": {"uz": "🔔 Aksiya xabarlari: ⛔️", "ru": "🔔 Рассылки: ⛔️", "en": "🔔 Promo messages: ⛔️"},
        "b_other_amount": {"uz": "✏️ O'z miqdorim", "ru": "✏️ Своё количество", "en": "✏️ Custom amount"},
        "b_other_sum": {"uz": "✏️ Boshqa summa", "ru": "✏️ Другая сумма", "en": "✏️ Other amount"},
        "b_retry": {"uz": "🔄 Qayta urinish", "ru": "🔄 Повторить", "en": "🔄 Try again"},
        "b_repeat": {"uz": "🔁 Takrorlash", "ru": "🔁 Повторить заказ", "en": "🔁 Repeat order"},
        "b_sub_check": {"uz": "✅ Obuna bo'ldim", "ru": "✅ Я подписался", "en": "✅ I subscribed"},
        "who_title": {"uz": "{prod} › Kimga", "ru": "{prod} › Кому", "en": "{prod} › Recipient"},
        "who_ask": {"uz": "Kimga kerak?", "ru": "Кому нужно?", "en": "Who is it for?"},
        "no_username_note": {
            "uz": "ℹ️ Sizda username yo'q — faqat ⭐ Stars bilan to'lash mumkin. Username o'rnatish: Telegram → Sozlamalar → Username.",
            "ru": "ℹ️ У вас нет username — доступна только оплата ⭐ Stars. Установить: Telegram → Настройки → Имя пользователя.",
            "en": "ℹ️ You have no username — only ⭐ Stars payment is available. Set one in Telegram → Settings → Username.",
        },
        "ask_username": {
            "uz": "🎁 Qabul qiluvchining username'ini yuboring\nMasalan: <code>@durov</code>\n\nYoki pastdagi tugma orqali kontaktdan tanlang.",
            "ru": "🎁 Отправьте username получателя\nНапример: <code>@durov</code>\n\nИли выберите контакт кнопкой ниже.",
            "en": "🎁 Send the recipient's username\nFor example: <code>@durov</code>\n\nOr pick a contact with the button below.",
        },
        "username_found": {
            "uz": "✅ Topildi: <b>{name}</b> (@{u})\n\nShu foydalanuvchiga sovg'a qilinsinmi?",
            "ru": "✅ Найден: <b>{name}</b> (@{u})\n\nОформить подарок этому пользователю?",
            "en": "✅ Found: <b>{name}</b> (@{u})\n\nSend the gift to this user?",
        },
        "username_bad": {
            "uz": "❌ Username noto'g'ri (5–32 belgi: a–z, 0–9, _). Qayta yuboring.",
            "ru": "❌ Неверный username (5–32 символа: a–z, 0–9, _). Отправьте снова.",
            "en": "❌ Invalid username (5–32 chars: a–z, 0–9, _). Send again.",
        },
        "username_notfound": {"uz": "❌ @{u} topilmadi.", "ru": "❌ @{u} не найден.", "en": "❌ @{u} was not found."},
        "username_cannot": {
            "uz": "❌ Bu foydalanuvchi hozir Premium qabul qila olmaydi.",
            "ru": "❌ Этот пользователь сейчас не может получить Premium.",
            "en": "❌ This user cannot receive Premium right now.",
        },
        "months_title": {
            "uz": "💎 Premium › Muddat\n👤 Qabul qiluvchi: {who}\n\nMuddatni tanlang:",
            "ru": "💎 Premium › Срок\n👤 Получатель: {who}\n\nВыберите срок:",
            "en": "💎 Premium › Duration\n👤 Recipient: {who}\n\nChoose a duration:",
        },
        "plan_btn": {
            "uz": "{badge}{months} oy · {price}",
            "ru": "{badge}{months} мес. · {price}",
            "en": "{badge}{months} mo · {price}",
        },
        "plan_soon": {"uz": "1 oy · tez kunda", "ru": "1 мес. · скоро", "en": "1 mo · coming soon"},
        "plan_soon_toast": {
            "uz": "Telegram hozircha 1 oylik sovg'ani qo'llamaydi",
            "ru": "Telegram пока не поддерживает подарок на 1 месяц",
            "en": "Telegram doesn't support 1-month gifts yet",
        },
        "months_note": {
            "uz": "💡 Telegram ichidagi narxdan arzon",
            "ru": "💡 Дешевле, чем в Telegram",
            "en": "💡 Cheaper than inside Telegram",
        },
        "stars_title": {
            "uz": "⭐ Stars › Paket\n👤 Kimga: {who}\n\nPaketni tanlang:",
            "ru": "⭐ Stars › Пакет\n👤 Кому: {who}\n\nВыберите пакет:",
            "en": "⭐ Stars › Package\n👤 For: {who}\n\nChoose a package:",
        },
        "ask_stars_amount": {
            "uz": "✏️ Necha ⭐ kerak? (50 dan {max} gacha butun son)",
            "ru": "✏️ Сколько ⭐ нужно? (целое число от 50 до {max})",
            "en": "✏️ How many ⭐? (whole number from 50 to {max})",
        },
        "bad_number": {
            "uz": "❌ Noto'g'ri qiymat. Qayta yuboring.",
            "ru": "❌ Неверное значение. Отправьте снова.",
            "en": "❌ Invalid value. Send again.",
        },
        "summary": {
            "uz": "🧾 <b>Buyurtma</b>\n━━━━━━━━━━━━━━━━\n{what}\n👤 Kimga: {who}\n💵 Narx: <b>{price}</b> ≈ {uzs}{promo}\n━━━━━━━━━━━━━━━━\nTo'lov usulini tanlang:",
            "ru": "🧾 <b>Заказ</b>\n━━━━━━━━━━━━━━━━\n{what}\n👤 Кому: {who}\n💵 Цена: <b>{price}</b> ≈ {uzs}{promo}\n━━━━━━━━━━━━━━━━\nВыберите способ оплаты:",
            "en": "🧾 <b>Order</b>\n━━━━━━━━━━━━━━━━\n{what}\n👤 For: {who}\n💵 Price: <b>{price}</b> ≈ {uzs}{promo}\n━━━━━━━━━━━━━━━━\nChoose a payment method:",
        },
        "what_prem": {
            "uz": "💎 Telegram Premium · {months} oy",
            "ru": "💎 Telegram Premium · {months} мес.",
            "en": "💎 Telegram Premium · {months} mo",
        },
        "what_star": {
            "uz": "⭐ Telegram Stars · {amount}",
            "ru": "⭐ Telegram Stars · {amount}",
            "en": "⭐ Telegram Stars · {amount}",
        },
        "promo_line": {
            "uz": "\n🎟 Promokod: −{discount}",
            "ru": "\n🎟 Промокод: −{discount}",
            "en": "\n🎟 Promo code: −{discount}",
        },
        "m_ton": {"uz": "💎 TON · {amount} TON", "ru": "💎 TON · {amount} TON", "en": "💎 TON · {amount} TON"},
        "m_stars": {"uz": "⭐ Stars · {amount} ⭐", "ru": "⭐ Stars · {amount} ⭐", "en": "⭐ Stars · {amount} ⭐"},
        "m_balance": {
            "uz": "💼 Balansdan · {amount}",
            "ru": "💼 С баланса · {amount}",
            "en": "💼 From balance · {amount}",
        },
        "m_balance_low": {
            "uz": "💼 Balans yetarli emas",
            "ru": "💼 Недостаточно средств",
            "en": "💼 Insufficient balance",
        },
        "balance_low_toast": {
            "uz": "Balans yetarli emas. Avval to'ldiring.",
            "ru": "Недостаточно средств. Сначала пополните.",
            "en": "Insufficient balance. Top up first.",
        },
        "ask_promo": {"uz": "🎟 Promokodni yuboring:", "ru": "🎟 Отправьте промокод:", "en": "🎟 Send the promo code:"},
        "promo_ok": {"uz": "✅ Promokod qo'llandi", "ru": "✅ Промокод применён", "en": "✅ Promo code applied"},
        "promo_bad": {
            "uz": "❌ Promokod yaroqsiz ({why})",
            "ru": "❌ Промокод недействителен ({why})",
            "en": "❌ Invalid promo code ({why})",
        },
        "ton_screen": {
            "uz": "💎 <b>TON orqali to'lov</b>\n━━━━━━━━━━━━━━━━\nSumma: <code>{amount}</code> TON\nManzil: <code>{address}</code>\nIzoh: <code>{comment}</code> ← MAJBURIY\n⏳ {minutes} daqiqa ichida to'lang\n━━━━━━━━━━━━━━━━\n❗️ Izohni yozmasangiz to'lov avtomatik aniqlanmaydi.\n💡 Eng oson yo'l — «Hamyon orqali to'lash».",
            "ru": "💎 <b>Оплата TON</b>\n━━━━━━━━━━━━━━━━\nСумма: <code>{amount}</code> TON\nАдрес: <code>{address}</code>\nКомментарий: <code>{comment}</code> ← ОБЯЗАТЕЛЬНО\n⏳ Оплатите в течение {minutes} мин.\n━━━━━━━━━━━━━━━━\n❗️ Без комментария платёж не определится автоматически.\n💡 Проще всего — «Оплатить через кошелёк».",
            "en": "💎 <b>Pay with TON</b>\n━━━━━━━━━━━━━━━━\nAmount: <code>{amount}</code> TON\nAddress: <code>{address}</code>\nComment: <code>{comment}</code> ← REQUIRED\n⏳ Pay within {minutes} min\n━━━━━━━━━━━━━━━━\n❗️ Without the comment the payment can't be detected automatically.\n💡 The easiest way is “Pay with wallet”.",
        },
        "ton_unconfigured": {
            "uz": "⚠️ TON to'lovi vaqtincha mavjud emas. Boshqa usulni tanlang.",
            "ru": "⚠️ Оплата TON временно недоступна. Выберите другой способ.",
            "en": "⚠️ TON payments are temporarily unavailable. Choose another method.",
        },
        "check_pending": {
            "uz": "⏳ To'lov hali kelmadi. Biroz kuting va qayta tekshiring.",
            "ru": "⏳ Платёж пока не поступил. Подождите и проверьте снова.",
            "en": "⏳ Payment hasn't arrived yet. Wait a bit and check again.",
        },
        "invoice_title_prem": {
            "uz": "Telegram Premium · {months} oy",
            "ru": "Telegram Premium · {months} мес.",
            "en": "Telegram Premium · {months} mo",
        },
        "invoice_title_topup": {"uz": "Balansni to'ldirish", "ru": "Пополнение баланса", "en": "Balance top-up"},
        "invoice_desc": {
            "uz": "Buyurtma {oid} · Soft-tg-Market",
            "ru": "Заказ {oid} · Soft-tg-Market",
            "en": "Order {oid} · Soft-tg-Market",
        },
        "stars_invoice_hint": {
            "uz": "⭐ To'lov hisobi yuborildi — pastdagi tugmani bosing.",
            "ru": "⭐ Счёт отправлен — нажмите кнопку ниже.",
            "en": "⭐ Invoice sent — press the button below.",
        },
        "balance_pay": {
            "uz": "💼 <b>Balansdan to'lov</b>\nNarx: {price}\nBalans: {balance} → to'lovdan keyin {after}",
            "ru": "💼 <b>Оплата с баланса</b>\nЦена: {price}\nБаланс: {balance} → после оплаты {after}",
            "en": "💼 <b>Pay from balance</b>\nPrice: {price}\nBalance: {balance} → after payment {after}",
        },
        "order_status_paid": {
            "uz": "🧾 Buyurtma <code>{oid}</code>\n\n✅ To'lov qabul qilindi\n⏳ Faollashtirilmoqda...",
            "ru": "🧾 Заказ <code>{oid}</code>\n\n✅ Оплата получена\n⏳ Активируем...",
            "en": "🧾 Order <code>{oid}</code>\n\n✅ Payment received\n⏳ Activating...",
        },
        "order_cancelled": {"uz": "🚫 Buyurtma bekor qilindi.", "ru": "🚫 Заказ отменён.", "en": "🚫 Order cancelled."},
        "order_closed": {
            "uz": "Bu buyurtma allaqachon yopilgan.",
            "ru": "Этот заказ уже закрыт.",
            "en": "This order is already closed.",
        },
        "wallet": {
            "uz": "💼 <b>Hamyon</b>\n━━━━━━━━━━━━━━━━\nBalans: <b>{usd}</b>\n≈ {uzs} · ≈ {ton} TON\n━━━━━━━━━━━━━━━━\nBalans bilan xarid — bir bosishda ⚡️",
            "ru": "💼 <b>Кошелёк</b>\n━━━━━━━━━━━━━━━━\nБаланс: <b>{usd}</b>\n≈ {uzs} · ≈ {ton} TON\n━━━━━━━━━━━━━━━━\nПокупки с баланса — в один клик ⚡️",
            "en": "💼 <b>Wallet</b>\n━━━━━━━━━━━━━━━━\nBalance: <b>{usd}</b>\n≈ {uzs} · ≈ {ton} TON\n━━━━━━━━━━━━━━━━\nBuy from balance in one tap ⚡️",
        },
        "topup_method": {
            "uz": "➕ To'ldirish usulini tanlang:",
            "ru": "➕ Выберите способ пополнения:",
            "en": "➕ Choose a top-up method:",
        },
        "topup_amount": {
            "uz": "➕ Summani tanlang ($):",
            "ru": "➕ Выберите сумму ($):",
            "en": "➕ Choose an amount ($):",
        },
        "ask_topup_amount": {
            "uz": "✏️ Summani yuboring ($, {min}–{max}):",
            "ru": "✏️ Отправьте сумму ($, {min}–{max}):",
            "en": "✏️ Send the amount ($, {min}–{max}):",
        },
        "history_title": {
            "uz": "📜 <b>Balans tarixi</b> ({page})",
            "ru": "📜 <b>История баланса</b> ({page})",
            "en": "📜 <b>Balance history</b> ({page})",
        },
        "history_empty": {
            "uz": "Hozircha operatsiyalar yo'q.",
            "ru": "Операций пока нет.",
            "en": "No transactions yet.",
        },
        "orders_title": {"uz": "📦 <b>Buyurtmalarim</b>", "ru": "📦 <b>Мои заказы</b>", "en": "📦 <b>My orders</b>"},
        "orders_empty": {"uz": "Hali buyurtmalar yo'q.", "ru": "Заказов пока нет.", "en": "No orders yet."},
        "order_card": {
            "uz": "🧾 <b>{oid}</b> · {status}\n{what}\n👤 {who}\n💵 {price}\n🕐 {date}",
            "ru": "🧾 <b>{oid}</b> · {status}\n{what}\n👤 {who}\n💵 {price}\n🕐 {date}",
            "en": "🧾 <b>{oid}</b> · {status}\n{what}\n👤 {who}\n💵 {price}\n🕐 {date}",
        },
        "st_awaiting_payment": {"uz": "⏳ to'lov kutilmoqda", "ru": "⏳ ожидает оплаты", "en": "⏳ awaiting payment"},
        "st_paid": {"uz": "💳 to'landi", "ru": "💳 оплачен", "en": "💳 paid"},
        "st_processing": {"uz": "⚙️ bajarilmoqda", "ru": "⚙️ выполняется", "en": "⚙️ processing"},
        "st_completed": {"uz": "✅ bajarildi", "ru": "✅ выполнен", "en": "✅ completed"},
        "st_failed": {"uz": "❌ xato", "ru": "❌ ошибка", "en": "❌ failed"},
        "st_needs_review": {"uz": "🔍 tekshirilmoqda", "ru": "🔍 проверяется", "en": "🔍 under review"},
        "st_refunded": {"uz": "↩️ qaytarildi", "ru": "↩️ возвращён", "en": "↩️ refunded"},
        "st_expired": {"uz": "⌛️ muddati o'tdi", "ru": "⌛️ истёк", "en": "⌛️ expired"},
        "st_cancelled": {"uz": "🚫 bekor qilindi", "ru": "🚫 отменён", "en": "🚫 cancelled"},
        "referral": {
            "uz": "👥 <b>Do'stlarni taklif qiling</b>\n\nHar bir do'stingiz xarididan <b>{percent}%</b> bonus balansingizga tushadi.\n\n🔗 Havolangiz:\n<code>{link}</code>\n\n👤 Taklif qilinganlar: <b>{invited}</b>\n💰 Jami bonus: <b>{earned}</b>",
            "ru": "👥 <b>Приглашайте друзей</b>\n\nС каждой покупки друга <b>{percent}%</b> бонусом на ваш баланс.\n\n🔗 Ваша ссылка:\n<code>{link}</code>\n\n👤 Приглашено: <b>{invited}</b>\n💰 Всего бонусов: <b>{earned}</b>",
            "en": "👥 <b>Invite friends</b>\n\nGet <b>{percent}%</b> of every friend's purchase as balance bonus.\n\n🔗 Your link:\n<code>{link}</code>\n\n👤 Invited: <b>{invited}</b>\n💰 Total bonus: <b>{earned}</b>",
        },
        "share_text": {
            "uz": "💎 Telegram Premium va ⭐ Stars eng arzon narxda!",
            "ru": "💎 Telegram Premium и ⭐ Stars по лучшей цене!",
            "en": "💎 Telegram Premium and ⭐ Stars at the lowest price!",
        },
        "settings": {"uz": "⚙️ <b>Sozlamalar</b>", "ru": "⚙️ <b>Настройки</b>", "en": "⚙️ <b>Settings</b>"},
        "help": {
            "uz": "🆘 <b>Yordam</b>\n\n❓ <b>Ko'p so'raladigan savollar</b>\n• Premium qancha vaqtda faollashadi? — Odatda 1–3 daqiqa.\n• Username'im yo'q, nima qilaman? — Telegram → Sozlamalar → Username.\n• To'ladim, lekin «kutilmoqda»? — «🔄 To'lovni tekshirish»ni bosing; izoh yozilmagan bo'lsa supportga yozing.\n• 1 oylik Premium bormi? — Telegram hozircha faqat 3, 6, 12 oylik sovg'aga ruxsat beradi.\n• Pulim qaytadimi? — Buyurtma bajarilmasa, pul avtomatik qaytariladi.",
            "ru": "🆘 <b>Помощь</b>\n\n❓ <b>Частые вопросы</b>\n• Как быстро активируется Premium? — Обычно 1–3 минуты.\n• У меня нет username — что делать? — Telegram → Настройки → Имя пользователя.\n• Оплатил, но «ожидает»? — Нажмите «🔄 Проверить оплату»; если комментарий не указан — напишите в поддержку.\n• Есть Premium на 1 месяц? — Telegram пока разрешает дарить только на 3, 6, 12 месяцев.\n• Вернут ли деньги? — Если заказ не выполнен, деньги возвращаются автоматически.",
            "en": "🆘 <b>Help</b>\n\n❓ <b>FAQ</b>\n• How fast is Premium activated? — Usually 1–3 minutes.\n• I have no username — what now? — Telegram → Settings → Username.\n• I paid but it says “waiting”? — Press “🔄 Check payment”; if you forgot the comment, contact support.\n• Is there 1-month Premium? — Telegram currently only allows gifting 3, 6 or 12 months.\n• Will I get a refund? — If the order fails, the money is returned automatically.",
        },
        "need_subscription": {
            "uz": "📢 Botdan foydalanish uchun kanallarga obuna bo'ling:",
            "ru": "📢 Для использования бота подпишитесь на каналы:",
            "en": "📢 Subscribe to the channels to use the bot:",
        },
        "not_subscribed": {
            "uz": "Hali obuna bo'lmadingiz",
            "ru": "Вы ещё не подписаны",
            "en": "You haven't subscribed yet",
        },
        "maintenance": {
            "uz": "🛠 Botda texnik ishlar olib borilmoqda. Tez orada qaytamiz!",
            "ru": "🛠 Ведутся технические работы. Скоро вернёмся!",
            "en": "🛠 Maintenance in progress. We'll be back soon!",
        },
        "banned": {
            "uz": "⛔️ Hisobingiz bloklangan. Savollar bo'lsa: {support}",
            "ru": "⛔️ Ваш аккаунт заблокирован. Вопросы: {support}",
            "en": "⛔️ Your account is blocked. Questions: {support}",
        },
        "error_generic": {
            "uz": "⚠️ Xatolik yuz berdi. Qayta urinib ko'ring.",
            "ru": "⚠️ Произошла ошибка. Попробуйте ещё раз.",
            "en": "⚠️ Something went wrong. Please try again.",
        },
        "use_menu": {"uz": "Menyudan foydalaning 👇", "ru": "Используйте меню 👇", "en": "Please use the menu 👇"},
        "cancelled": {"uz": "Bekor qilindi.", "ru": "Отменено.", "en": "Cancelled."},
        "throttle": {"uz": "⏳ Sekinroq", "ru": "⏳ Помедленнее", "en": "⏳ Slow down"},
        "err_METHOD_DISABLED": {
            "uz": "Bu to'lov usuli hozir o'chirilgan.",
            "ru": "Этот способ оплаты сейчас отключён.",
            "en": "This payment method is currently disabled.",
        },
        "err_PLAN_UNAVAILABLE": {
            "uz": "Bu tarif hozir mavjud emas.",
            "ru": "Этот тариф сейчас недоступен.",
            "en": "This plan is currently unavailable.",
        },
        "err_RATE_LIMITED": {
            "uz": "Juda ko'p urinish. Biroz kuting.",
            "ru": "Слишком много попыток. Подождите.",
            "en": "Too many attempts. Please wait.",
        },
        "err_INSUFFICIENT_BALANCE": {
            "uz": "Balans yetarli emas.",
            "ru": "Недостаточно средств.",
            "en": "Insufficient balance.",
        },
        "err_VALIDATION_ERROR": {"uz": "Noto'g'ri ma'lumot.", "ru": "Неверные данные.", "en": "Invalid data."},
    }
)
