"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 00:37:17.968090

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='bot', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('segment', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'running', 'paused', 'completed', 'cancelled', 'failed', name='broadcaststatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cursor_user_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('invite_link', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('daily_stats',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('paying_users', sa.Integer(), nullable=False),
    sa.Column('orders_created', sa.Integer(), nullable=False),
    sa.Column('orders_completed', sa.Integer(), nullable=False),
    sa.Column('orders_failed', sa.Integer(), nullable=False),
    sa.Column('orders_refunded', sa.Integer(), nullable=False),
    sa.Column('premium_3m', sa.Integer(), nullable=False),
    sa.Column('premium_6m', sa.Integer(), nullable=False),
    sa.Column('premium_12m', sa.Integer(), nullable=False),
    sa.Column('stars_orders', sa.Integer(), nullable=False),
    sa.Column('stars_sold', sa.Integer(), nullable=False),
    sa.Column('cash_in_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('revenue_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('gross_profit_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('expenses_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('referral_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_profit_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('revenue_by_method', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avg_delivery_seconds', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pair', sa.String(length=16), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rates_pair_time', 'exchange_rates', ['pair', sa.literal_column('fetched_at DESC')], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('category', sa.Enum('server', 'domain', 'fragment_fee', 'network_fee', 'advertising', 'salary', 'other', name='expensecategory'), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('months', sa.SmallInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('provider_supported', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('cost_ton', sa.Numeric(precision=20, scale=9), nullable=True),
    sa.Column('cost_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('markup_percent', sa.Numeric(precision=6, scale=2), server_default='8', nullable=False),
    sa.Column('fixed_markup_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('fixed_price_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('price_stars', sa.Integer(), nullable=True),
    sa.Column('reference_price_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('badge', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.CheckConstraint('months IN (1,3,6,12)', name='ck_plan_months'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('months')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('percent', 'fixed_usd', name='promotype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('applies_to', sa.Enum('all', 'premium', 'stars', name='productscope'), nullable=False),
    sa.Column('min_order_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('per_user_limit', sa.Integer(), server_default='1', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_promo_code_upper', 'promo_codes', [sa.literal_column('upper(code)')], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('star_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_popular', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.CheckConstraint('amount >= 50', name='ck_pkg_min'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amount')
    )
    op.create_table('unmatched_ton_txs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tx_hash', sa.String(length=64), nullable=False),
    sa.Column('amount_ton', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=68), nullable=True),
    sa.Column('resolution', sa.String(length=64), server_default='pending', nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_table('user_daily_activity',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('day', 'user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=5), server_default='uz', nullable=False),
    sa.Column('balance_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ban_reason', sa.String(length=255), nullable=True),
    sa.Column('is_bot_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('marketing_opt_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tg_is_premium', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('total_spent_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_usd >= 0', name='ck_users_balance_nonneg'),
    sa.CheckConstraint('referrer_id <> id', name='ck_users_not_self_referrer'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_referrer_id', 'users', ['referrer_id'], unique=False)
    op.create_index('ix_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=False)
    op.create_table('admins',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'support', name='adminrole'), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('balance_transactions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('type', sa.Enum('topup', 'purchase', 'refund', 'referral_bonus', 'referral_revoke', 'admin_credit', 'admin_debit', 'late_payment', 'overpayment', 'underpayment', name='balancetxtype'), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_baltx_user_created', 'balance_transactions', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.Enum('premium', 'stars', name='producttype'), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('plan_months', sa.SmallInteger(), nullable=True),
    sa.Column('stars_amount', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.Enum('self', 'other', name='recipienttype'), nullable=False),
    sa.Column('recipient_username', sa.String(length=32), nullable=True),
    sa.Column('recipient_user_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('awaiting_payment', 'paid', 'processing', 'completed', 'failed', 'needs_review', 'refunded', 'expired', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('ton', 'stars', 'balance', name='paymentmethod'), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('discount_usd', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=30, scale=9), nullable=True),
    sa.Column('price_currency', sa.String(length=8), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=30, scale=9), nullable=True),
    sa.Column('cost_currency', sa.String(length=8), nullable=True),
    sa.Column('profit_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('provider', sa.Enum('fragment_direct', 'fragment_api', 'bot_stars', 'manual', 'mock', name='providercode'), nullable=True),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('bot_message_id', sa.BigInteger(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars_amount IS NULL OR stars_amount >= 50', name='ck_orders_stars'),
    sa.ForeignKeyConstraint(['plan_id'], ['premium_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_orders_idem')
    )
    op.create_index('ix_orders_completed_at', 'orders', ['completed_at'], unique=False, postgresql_where=sa.text("status = 'completed'"))
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_queue', 'orders', ['status', 'next_attempt_at'], unique=False, postgresql_where=sa.text("status IN ('paid','processing','needs_review')"))
    op.create_index('ix_orders_user_created', 'orders', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('order_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.Enum('awaiting_payment', 'paid', 'processing', 'completed', 'failed', 'needs_review', 'refunded', 'expired', 'cancelled', name='orderstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('awaiting_payment', 'paid', 'processing', 'completed', 'failed', 'needs_review', 'refunded', 'expired', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_events_order', 'order_events', ['order_id', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.Enum('order', 'topup', name='paymentpurpose'), nullable=False),
    sa.Column('method', sa.Enum('ton', 'stars', 'balance', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'expired', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=9), nullable=False),
    sa.Column('received_amount', sa.Numeric(precision=30, scale=9), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rate_used', sa.Numeric(precision=20, scale=9), nullable=True),
    sa.Column('ton_comment', sa.String(length=32), nullable=True),
    sa.Column('ton_tx_hash', sa.String(length=64), nullable=True),
    sa.Column('ton_sender', sa.String(length=68), nullable=True),
    sa.Column('tg_charge_id', sa.String(length=128), nullable=True),
    sa.Column('is_late', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('tg_charge_id'),
    sa.UniqueConstraint('ton_comment'),
    sa.UniqueConstraint('ton_tx_hash')
    )
    op.create_index('ix_payments_confirmed_at', 'payments', ['confirmed_at'], unique=False)
    op.create_index('ix_payments_pending', 'payments', ['status', 'expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_payments_user_created', 'payments', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('promo_redemptions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_id', 'order_id', name='uq_promo_order')
    )
    op.create_table('referral_rewards',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('credited', 'revoked', name='rewardstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('hot_wallet_transactions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='direction'), nullable=False),
    sa.Column('kind', sa.Enum('user_payment', 'fulfillment', 'withdrawal', 'sweep', 'network_fee', 'manual_deposit', 'refund_out', 'other', name='hotwallettxkind'), nullable=False),
    sa.Column('amount_ton', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('fee_ton', sa.Numeric(precision=20, scale=9), server_default='0', nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rate_used', sa.Numeric(precision=20, scale=9), nullable=True),
    sa.Column('tx_hash', sa.String(length=64), nullable=True),
    sa.Column('counterparty', sa.String(length=68), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_table('stars_transactions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='direction'), nullable=False),
    sa.Column('kind', sa.Enum('payment_in', 'premium_gift', 'refund', 'withdrawal_manual', 'telegram_refund', name='starstxkind'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_charge_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stars_transactions')
    op.drop_table('hot_wallet_transactions')
    op.drop_table('referral_rewards')
    op.drop_table('promo_redemptions')
    op.drop_index('ix_payments_user_created', table_name='payments')
    op.drop_index('ix_payments_pending', table_name='payments', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_payments_confirmed_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_order_events_order', table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_orders_user_created', table_name='orders')
    op.drop_index('ix_orders_queue', table_name='orders', postgresql_where=sa.text("status IN ('paid','processing','needs_review')"))
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_completed_at', table_name='orders', postgresql_where=sa.text("status = 'completed'"))
    op.drop_table('orders')
    op.drop_index('ix_baltx_user_created', table_name='balance_transactions')
    op.drop_table('balance_transactions')
    op.drop_table('admins')
    op.drop_index('ix_users_username_lower', table_name='users')
    op.drop_index('ix_users_referrer_id', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_table('user_daily_activity')
    op.drop_table('unmatched_ton_txs')
    op.drop_table('star_packages')
    op.drop_table('settings')
    op.drop_index('uq_promo_code_upper', table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_table('premium_plans')
    op.drop_table('expenses')
    op.drop_index('ix_rates_pair_time', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_table('daily_stats')
    op.drop_table('channels')
    op.drop_table('broadcasts')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
    from app import models  # noqa: F401
    from app.core.db import Base
    bind = op.get_bind()
    for t in {c.type for tb in Base.metadata.tables.values() for c in tb.columns if isinstance(c.type, sa.Enum)}:
        t.drop(bind, checkfirst=True)
